Symphony/Controllers/enrollsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Symphony;

namespace Symphony.Controllers
{
    public class enrollsController : Controller
    {
        private Database1Entities6 db = new Database1Entities6();

        // GET: enrolls
        public ActionResult Index()
        {
            var enrolls = db.enrolls.Include(e => e.cours);
            return View(enrolls.ToList());
        }

        public ActionResult Index_view()
        {
            var data = db.entance_exams.ToList();
            return View(data);
        }

        // GET: enrolls/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            enroll enroll = db.enrolls.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }
            return View(enroll);
        }

        // GET: enrolls/Create
        public ActionResult Create()
        {
            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name");
            return View();
        }

        // POST: enrolls/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "enroll_id,s_name,cell,c_id")] enroll enroll)
        {
            enroll e = db.enrolls.Where(x => x.cell == enroll.cell).FirstOrDefault();
            if (ModelState.IsValid)
            {
                if (e == null)
                {
                    db.enrolls.Add(enroll);
                    db.SaveChanges();
                    TempData["message"] = "<script>alert('Successfully Enrolled')</script>";
                    return RedirectToAction("Index" , "Home");
                }
                else
                {
                    ViewData["message"] = "Records already exists";
                }
               
            }

            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name", enroll.c_id);
            return View(enroll);
        }

        // GET: enrolls/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            enroll enroll = db.enrolls.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }
            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name", enroll.c_id);
            return View(enroll);
        }

        // POST: enrolls/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "enroll_id,s_name,cell,c_id")] enroll enroll)
        {
            enroll e = db.enrolls.Where(x => x.cell == enroll.cell).FirstOrDefault();

            if (ModelState.IsValid)
            {
                if (e == null)
                {
                    db.Entry(enroll).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewData["message"] = "Records already exists , please update different";
                }
                
            }
            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name", enroll.c_id);
            return View(enroll);
        }

        // GET: enrolls/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            enroll enroll = db.enrolls.Find(id);
            if (enroll == null)
            {
                return HttpNotFound();
            }
            return View(enroll);
        }

        // POST: enrolls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            enroll enroll = db.enrolls.Find(id);
            db.enrolls.Remove(enroll);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Symphony/Controllers/entance_examsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Symphony;

namespace Symphony.Controllers
{
    public class entance_examsController : Controller
    {
        private Database1Entities6 db = new Database1Entities6();

        // GET: entance_exams
        public ActionResult Index()
        {
            var entance_exams = db.entance_exams.Include(e => e.enroll);
            return View(entance_exams.ToList());
        }


        public ActionResult Index_view(string search)
        {
          
            if (search == null)
            {
                var data = db.entance_exams.ToList();
                return View(data);
            }
            else
            {
                return View(db.entance_exams.Where(x => x.s_name == search).ToList());
            }
          
        }

        // GET: entance_exams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            entance_exams entance_exams = db.entance_exams.Find(id);
            if (entance_exams == null)
            {
                return HttpNotFound();
            }
            return View(entance_exams);
        }

        // GET: entance_exams/Create
        public ActionResult Create()
        {
            ViewBag.roll_num = new SelectList(db.enrolls, "enroll_id", "enroll_id");
            ViewBag.s_name = new SelectList(db.enrolls, "enroll_id", "s_name");
            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name");
            return View();
        }

        // POST: entance_exams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "roll_num,marks,c_id,fees,s_name,cell")] entance_exams entance_exams)
        {

            entance_exams ee = db.entance_exams.Where(x => x.roll_num == entance_exams.roll_num).FirstOrDefault();
           

            if (ModelState.IsValid)
            {
                if (ee == null)
                {
                    if (entance_exams.marks < 50)
                    {
                        ViewBag.msg = "Marks are less than 50 , Student is Failed , cannot enter data";
                    }
                    else if(entance_exams.marks > 100)
                    {
                        ViewBag.msg = "Marks should be less than or equal to 100 Student is Failed , cannot enter data";
                        
                    }
                    else
                    {
                        db.entance_exams.Add(entance_exams);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                          
                        
                        
                    
                }
                else
                {
                    ViewData["a"] = "Roll number already exists";
                }
                    
               
               
                
            }

            ViewBag.roll_num = new SelectList(db.enrolls, "enroll_id", "enroll_id", entance_exams.roll_num);
            ViewBag.s_name = new SelectList(db.enrolls, "enroll_id", "s_name", entance_exams.roll_num);
            ViewBag.c_id = new SelectList(db.courses, "c_id", "c_name", entance_exams.roll_num);
            return View(entance_exams);
        }

        // GET: entance_exams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            entance_exams entance_exams = db.entance_exams.Find(id);
            if (entance_exams == null)
            {
                return HttpNotFound();
            }
            ViewBag.roll_num = new SelectList(db.enrolls, "enroll_id", "s_name", entance_exams.roll_num);
            return View(entance_exams);
        }

        // POST: entance_exams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "roll_num,marks,c_id,fees,s_name,cell")] entance_exams entance_exams)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entance_exams).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.roll_num = new SelectList(db.enrolls, "enroll_id", "s_name", entance_exams.roll_num);
            return View(entance_exams);
        }

        // GET: entance_exams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            entance_exams entance_exams = db.entance_exams.Find(id);
            if (entance_exams == null)
            {
                return HttpNotFound();
            }
            return View(entance_exams);
        }

        // POST: entance_exams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            entance_exams entance_exams = db.entance_exams.Find(id);
            db.entance_exams.Remove(entance_exams);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Symphony/Views/Shared/_BackEndLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="~/BackEnd/images/favicon.ico" type="image/ico" />
    <title>Gentelella Alela! | </title>
    <!-- Bootstrap -->
    <link href="~/BackEnd/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/BackEnd/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/BackEnd/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/BackEnd/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="~/BackEnd/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="~/BackEnd/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="~/BackEnd/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="~/BackEnd/build/css/custom.min.css" rel="stylesheet">
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="@Url.Action("Index", "Home")" class="site_title"><i class="fa fa-paw"></i> <span>SYMPHONY</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="~/BackEnd/production/images/img.jpg" alt="~/BackEnd." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>Welcome @Session["username"]</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Index <span class="fa fa-chevron-down"></span></a>

                                </li>

                                <li>
                                    <a href="@Url.Action("Index", "entance_exams")"><i class="fa fa-edit"></i> Exam details</a>

                                </li>

                                <li>
                                    <a href="@Url.Action("Index", "enrolls")"><i class="fa fa-edit"></i> Enrolled Students </a>

                                </li>

                                <li>
                                    <a href="@Url.Action("contact_admin_view", "Home")"><i class="fa fa-edit"></i> Locations | Contact </a>

                                </li>


                                <li>
                                    <a href="@Url.Action("Index", "entance_exams")"><i class="fa fa-table"></i> Student Details</a>

                                </li>
                                <li>
                                    <a href="@Url.Action("admin_course_view", "Home")"><i class="fa fa-bar-chart-o"></i> Courses </a>

                                </li>

                                <li>
                                    <a href="@Url.Action("admin_lectures_view", "Home")"><i class="fa fa-bar-chart-o"></i> Course Lectures </a>

                                </li>

                               


                                <li>
                                    <a href="@Url.Action("admin_faq_view", "Home")"><i class="fa fa-bar-chart-o"></i> FAQ'S </a>

                                </li>

                                @*<li>
            <a><i class="fa fa-clone"></i>  <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
                <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                <li><a href="fixed_footer.html">Fixed Footer</a></li>
            </ul>
        </li>*@
                            </ul>
                        </div>
                        @*<div class="menu_section">
                            <h3>Live On</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="e_commerce.html">E-commerce</a></li>
                                        <li><a href="projects.html">Projects</a></li>
                                        <li><a href="project_detail.html">Project Detail</a></li>
                                        <li><a href="contacts.html">Contacts</a></li>
                                        <li><a href="profile.html">Profile</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="page_403.html">403 Error</a></li>
                                        <li><a href="page_404.html">404 Error</a></li>
                                        <li><a href="page_500.html">500 Error</a></li>
                                        <li><a href="plain_page.html">Plain Page</a></li>
                                        <li><a href="login.html">Login Page</a></li>
                                        <li><a href="pricing_tables.html">Pricing Tables</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="#level1_1">Level One</a>
                                        <li>
                                            <a>Level One<span class="fa fa-chevron-down"></span></a>
                                            <ul class="nav child_menu">
                                                <li class="sub_menu">
                                                    <a href="level2.html">Level Two</a>
                                                </li>
                                                <li>
                                                    <a href="#level2_1">Level Two</a>
                                                </li>
                                                <li>
                                                    <a href="#level2_2">Level Two</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#level1_2">Level One</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
                            </ul>
                        </div>*@
                    </div>
                    <!-- /sidebar menu -->

                   

                    <!-- /menu footer buttons -->
                    
                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <nav class="nav navbar-nav">
                        <ul class=" navbar-right">
                            <li class="nav-item dropdown open" style="padding-left: 15px;">
                                <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                    <img src="~/BackEnd/images/img.jpg" alt="">@Session["username"]
                                </a>

                            </li>
                            <li><a href="@Url.Action("logout", "Home")"><i class="ti-user"></i>LogOut</a></li>

                        </ul>
                            
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <br /><br />
            <div class="container" style="margin-left:400px; width:1400px; background-color:white; color:black; margin-top:20px; font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif; font-size:15px; padding:20px;">
                @RenderBody()
            </div>

            

            <!-- footer content -->
            @*<footer>
                <div class="pull-right">
                    Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
                </div>
                <div class="clearfix"></div>
            </footer>*@
            <!-- /footer content -->
        </div>
    </div>
    <!-- jQuery -->
    <script src="~/BackEnd/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/BackEnd/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="~/BackEnd/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/BackEnd/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/BackEnd/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="~/BackEnd/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="~/BackEnd/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="~/BackEnd/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="~/BackEnd/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="~/BackEnd/vendors/Flot/jquery.flot.js"></script>
    <script src="~/BackEnd/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="~/BackEnd/vendors/Flot/jquery.flot.time.js"></script>
    <script src="~/BackEnd/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="~/BackEnd/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="~/BackEnd/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="~/BackEnd/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="~/BackEnd/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="~/BackEnd/vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="~/BackEnd/vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="~/BackEnd/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="~/BackEnd/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/BackEnd/vendors/moment/min/moment.min.js"></script>
    <script src="~/BackEnd/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
    <!-- Custom Theme Scripts -->
    <script src="~/BackEnd/build/js/custom.min.js"></script>

</body>
</html>